apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicalrecordservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medicalrecordservice
  template:
    metadata:
      labels:
        app: medicalrecordservice
    spec:
      containers:
        - name: medicalrecordservice
          image: darthstranger/medicalrecordservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: medicalrecordservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: medicalrecordservice
  ports:
    - name: medicalrecordservice
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: medicalrecordservicegrpc
      protocol: TCP
      port: 666
      targetPort: 666