apiVersion: apps/v1
kind: Deployment
metadata:
  name: patientservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patientservice
  template:
    metadata:
      labels:
        app: patientservice
    spec:
      containers:
        - name: patientservice
          image: darthstranger/patientservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: patientservice-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: patientservice
  ports:
    - name: patientservice
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: patientgrpc
      protocol: TCP
      port: 666
      targetPort: 666